-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.3
-- Copyright 2000-2024 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.50.31;service_name=PROD;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;





CREATE OR REPLACE FUNCTION sf_get_cust_job_name (V_CUSTOMER_ID text) RETURNS varchar AS $body$
DECLARE

	V_RTN_VALUE varchar(40);

BEGIN
	SELECT CUST_JOB_NAME 
	INTO STRICT V_RTN_VALUE 
	FROM CUSTOMERS 
	WHERE CUSTOMER_ID = V_CUSTOMER_ID;
	RETURN V_RTN_VALUE;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION sf_get_cust_job_name (V_CUSTOMER_ID text) FROM PUBLIC;

-- Function SF_GET_CUST_JOB_NAME estimated cost: 4
	-- TEST => 2
	-- SIZE => 1




CREATE OR REPLACE FUNCTION sf_get_weekend (V_DATE timestamp(0)) RETURNS varchar AS $body$
DECLARE

	V_RTN_VALUE varchar(10);

BEGIN
	IF TO_CHAR(V_DATE,'D') = '0' THEN
	V_RTN_VALUE := '일요일';
	ELSIF TO_CHAR(V_DATE,'D') = '1' THEN
	V_RTN_VALUE := '월요일';
	ELSIF TO_CHAR(V_DATE,'D') ='2' THEN
	V_RTN_VALUE := '화요일';
	ELSIF TO_CHAR(V_DATE,'D') ='3' THEN
	V_RTN_VALUE := '수요일';
	ELSIF TO_CHAR(V_DATE,'D') ='4' THEN
	V_RTN_VALUE :='목요일';
	ELSIF TO_CHAR(V_DATE,'D') ='5' THEN
	V_RTN_VALUE :='금요일';
	ELSIF TO_CHAR(V_DATE,'D') ='6' THEN
	V_RTN_VALUE :='토요일';
END IF;
	RETURN V_RTN_VALUE;
END;
$body$
LANGUAGE PLPGSQL
SECURITY DEFINER
;
-- REVOKE ALL ON FUNCTION sf_get_weekend (V_DATE timestamp(0)) FROM PUBLIC;

-- Function SF_GET_WEEKEND estimated cost: 4
	-- TEST => 2
	-- SIZE => 1

-- Total number of functions: 2.
-- Total size of function code: 735 bytes.
-- Total estimated cost: 8 units, 1 person-day(s).
