-- Generated by Ora2Pg, the Oracle database Schema converter, version 24.3
-- Copyright 2000-2024 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=192.168.50.31;service_name=PROD;port=1521

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET check_function_bodies = false;



CREATE TABLE customers (
	customer_id varchar(21) NOT NULL,
	cust_first_name varchar(20) NOT NULL,
	cust_last_name varchar(20) NOT NULL,
	email varchar(172),
	birthday timestamp(0),
	phone_number varchar(325),
	gender varchar(1),
	wedding_type varchar(1),
	cust_job_name varchar(18)
) ;
ALTER TABLE customers ADD PRIMARY KEY (customer_id);
ALTER TABLE customers ALTER COLUMN cust_first_name SET NOT NULL;
ALTER TABLE customers ALTER COLUMN cust_last_name SET NOT NULL;


CREATE TABLE departments (
	department_id varchar(9) NOT NULL,
	department_name varchar(30) NOT NULL,
	manager_id integer,
	location_id varchar(9)
) ;
CREATE INDEX ix_departments_n1 ON departments (location_id);
ALTER TABLE departments ADD PRIMARY KEY (department_id);
ALTER TABLE departments ALTER COLUMN department_name SET NOT NULL;


CREATE TABLE employees (
	employee_id varchar(13) NOT NULL,
	first_name varchar(28),
	last_name varchar(33),
	email varchar(33),
	hire_date timestamp(0),
	job_id varchar(9),
	salary bigint,
	commission_pct decimal(2,2),
	department_id varchar(9)
) ;
CREATE INDEX ix_emplyees_n1 ON employees (department_id);
CREATE INDEX ix_emplyees_n2 ON employees (job_id);
CREATE INDEX ix_emplyees_n3 ON employees (email);
CREATE INDEX ix_emplyees_n4 ON employees (last_name);
ALTER TABLE employees ADD PRIMARY KEY (employee_id);


CREATE TABLE jobs (
	job_id varchar(9) NOT NULL,
	job_title varchar(35),
	min_salary bigint,
	max_salary bigint
) ;
ALTER TABLE jobs ADD PRIMARY KEY (job_id);


CREATE TABLE locations (
	location_id varchar(9) NOT NULL,
	street_address varchar(40),
	postal_code varchar(12),
	city varchar(30),
	state_province varchar(25),
	country_name varchar(40),
	region_name varchar(25)
) ;
ALTER TABLE locations ADD PRIMARY KEY (location_id);


CREATE TABLE orders (
	order_id varchar(20) NOT NULL,
	order_date timestamp(0),
	order_mode varchar(10),
	customer_id varchar(10),
	employee_id varchar(10),
	order_status bigint,
	order_total bigint
) ;

-- Function used in indexes must be immutable, use immutable_to_char() instead of to_char()
CREATE OR REPLACE FUNCTION immutable_to_char(timestamp, fmt text) RETURNS text AS
$$ SELECT to_char($1, $2); $$
LANGUAGE sql immutable;

CREATE INDEX ix_orders_n1 ON orders (order_date, order_mode, employee_id);
CREATE INDEX ix_orders_n2 ON orders (employee_id, order_date);
CREATE INDEX ix_orders_n3 ON orders (order_date);
CREATE INDEX ix_orders_n4 ON orders (order_date, employee_id);
CREATE INDEX ix_orders_n5 ON orders (immutable_to_char(order_date,'yyyymmdd'), employee_id);
CREATE INDEX ix_orders_n6 ON orders (customer_id, order_date, employee_id);
ALTER TABLE orders ADD PRIMARY KEY (order_id);


CREATE TABLE orders_paging (
	order_id bigint NOT NULL,
	order_date timestamp(0),
	order_mode varchar(10),
	customer_id varchar(10),
	employee_id varchar(10),
	order_status bigint,
	order_total bigint
) ;
CREATE INDEX ix_orders_paging_n1 ON orders_paging (order_date, order_status);
CREATE INDEX ix_orders_paging_n2 ON orders_paging (employee_id, order_date, order_status);
ALTER TABLE orders_paging ADD PRIMARY KEY (order_id);


CREATE UNLOGGED TABLE order_items (
	order_id varchar(33) NOT NULL,
	product_id varchar(13) NOT NULL,
	order_date timestamp(0),
	unit_price bigint,
	quantity bigint
) ;
CREATE INDEX ix_order_items_n1 ON order_items (order_date);
CREATE INDEX ix_order_items_n2 ON order_items (product_id, order_date);
CREATE INDEX ix_order_items_n3 ON order_items (order_id, order_date);
ALTER TABLE order_items ADD PRIMARY KEY (order_id,product_id);


CREATE UNLOGGED TABLE order_items_return (
	order_id varchar(33) NOT NULL,
	product_id varchar(13) NOT NULL,
	return_date timestamp(0),
	unit_price bigint,
	quantity bigint
) ;
CREATE INDEX ix_order_items_return_n1 ON order_items_return (return_date);
ALTER TABLE order_items_return ADD PRIMARY KEY (order_id,product_id);


CREATE TABLE products (
	product_id varchar(13) NOT NULL,
	product_name varchar(50),
	category_id smallint,
	weight_class smallint,
	warranty_period INTERVAL YEAR TO MONTH,
	supplier_id integer,
	product_status varchar(20),
	list_price bigint,
	min_price decimal(8,2),
	catalog_url varchar(50),
	product_description varchar(2000)
) ;
ALTER TABLE products ADD PRIMARY KEY (product_id);


CREATE TABLE sales (
	order_date varchar(8),
	order_mode varchar(6),
	customer_id varchar(21),
	employee_id varchar(13),
	product_id varchar(13),
	order_qty bigint,
	order_amt bigint
) ;
CREATE INDEX ix_sales_n1 ON sales (customer_id, order_date);
CREATE INDEX ix_sales_n2 ON sales (employee_id, order_date);
CREATE INDEX ix_sales_n3 ON sales (order_date, product_id);
CREATE INDEX ix_sales_n4 ON sales (product_id, order_date);
CREATE INDEX ix_sales_n5 ON sales (order_date, employee_id);


CREATE TABLE std_terms (
	term_id varchar(37),
	term_name varchar(1200),
	term_underbar_delimited varchar(300)
) ;


CREATE UNLOGGED TABLE tmp_hash_test1 (
	id bigint NOT NULL,
	seq bigint NOT NULL,
	val varchar(8)
) ;
ALTER TABLE tmp_hash_test1 ADD PRIMARY KEY (id,seq);


CREATE UNLOGGED TABLE tmp_hash_test2 (
	id bigint NOT NULL,
	seq bigint NOT NULL,
	rcnt bigint NOT NULL,
	amt bigint
) ;
ALTER TABLE tmp_hash_test2 ADD PRIMARY KEY (id,seq,rcnt);


CREATE TABLE tmp_std_terms (
	term_id varchar(10),
	term_name varchar(100),
	term_underbar_delimited varchar(300)
) ;
