#!/usr/bin/env python3
"""
한국 주식 분봉 데이터 수집기 - 오라클 최종 버전
TNS 설정을 사용한 hr/oracle@PROD 연결
"""

import cx_Oracle
import requests
import xml.etree.ElementTree as ET
from datetime import datetime, timedelta
import time
import os
import argparse

class StockOracleCollector:
    def __init__(self):
        # TNS 경로 설정
        os.environ['TNS_ADMIN'] = '/usr/lib/oracle/23/client64/lib/network/admin'
        
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }
        
        # 주요 종목들
        self.major_stocks = {
            '삼성전자': '005930',
            'SK하이닉스': '000660', 
            'NAVER': '035420',
            '카카오': '035720',
            'LG에너지솔루션': '373220',
            '삼성바이오로직스': '207940',
            '현대차': '005380',
            '기아': '000270',
            'LG전자': '066570',
            'KB금융': '105560'
        }
        
        self.connection = None
        
    def connect_db(self):
        """오라클 DB 연결 (TNS 사용)"""
        try:
            self.connection = cx_Oracle.connect('hr/oracle@PROD', encoding='UTF-8')
            print(f"✅ 오라클 DB 연결 성공 (PROD)")
            return True
            
        except Exception as e:
            print(f"❌ DB 연결 실패: {e}")
            return False
    
    def ensure_tables(self):
        """테이블 존재 확인 및 생성"""
        if not self.connection:
            return False
            
        cursor = self.connection.cursor()
        
        try:
            # 테이블 존재 확인
            cursor.execute("""
                SELECT COUNT(*) FROM USER_TABLES 
                WHERE TABLE_NAME IN ('STOCK_MINUTE_DATA', 'STOCK_INFO')
            """)
            
            table_count = cursor.fetchone()[0]
            
            if table_count < 2:
                print("📝 테이블 생성 중...")
                
                # 분봉 데이터 테이블
                cursor.execute("""
                CREATE TABLE STOCK_MINUTE_DATA (
                    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                    STOCK_CODE VARCHAR2(10) NOT NULL,
                    STOCK_NAME VARCHAR2(100),
                    TRADE_DATETIME DATE NOT NULL,
                    OPEN_PRICE NUMBER(10),
                    HIGH_PRICE NUMBER(10),
                    LOW_PRICE NUMBER(10),
                    CLOSE_PRICE NUMBER(10),
                    VOLUME NUMBER(15),
                    CREATED_DATE DATE DEFAULT SYSDATE,
                    CONSTRAINT PK_STOCK_MINUTE PRIMARY KEY (ID),
                    CONSTRAINT UK_STOCK_MINUTE UNIQUE (STOCK_CODE, TRADE_DATETIME)
                )
                """)
                
                # 종목 정보 테이블
                cursor.execute("""
                CREATE TABLE STOCK_INFO (
                    STOCK_CODE VARCHAR2(10) PRIMARY KEY,
                    STOCK_NAME VARCHAR2(100) NOT NULL,
                    MARKET_TYPE VARCHAR2(20),
                    SECTOR VARCHAR2(50),
                    LAST_UPDATED DATE DEFAULT SYSDATE
                )
                """)
                
                self.connection.commit()
                print("✅ 테이블 생성 완료")
            else:
                print("✅ 테이블이 이미 존재합니다")
            
            return True
            
        except Exception as e:
            print(f"❌ 테이블 생성 실패: {e}")
            return False
        finally:
            cursor.close()
    
    def get_minute_data(self, stock_code, count=240):
        """분봉 데이터 수집"""
        url = "https://fchart.stock.naver.com/sise.naver"
        params = {
            'timeframe': 'minute',
            'count': count,
            'requestType': 0,
            'symbol': stock_code
        }
        
        try:
            response = requests.get(url, params=params, headers=self.headers, timeout=15)
            response.encoding = 'euc-kr'
            
            if response.status_code != 200:
                return None
                
            root = ET.fromstring(response.text)
            chartdata = root.find('chartdata')
            
            if chartdata is None:
                return None
                
            stock_name = chartdata.get('name')
            items = chartdata.findall('item')
            
            minute_data = []
            
            for item in items:
                data = item.get('data')
                if not data:
                    continue
                    
                parts = data.split('|')
                if len(parts) < 6:
                    continue
                
                datetime_str = parts[0]
                open_price = parts[1] if parts[1] != 'null' else None
                high_price = parts[2] if parts[2] != 'null' else None
                low_price = parts[3] if parts[3] != 'null' else None
                close_price = parts[4] if parts[4] != 'null' else None
                volume = parts[5] if parts[5] != 'null' else None
                
                if len(datetime_str) >= 12:
                    try:
                        year = int(datetime_str[:4])
                        month = int(datetime_str[4:6])
                        day = int(datetime_str[6:8])
                        hour = int(datetime_str[8:10])
                        minute = int(datetime_str[10:12])
                        
                        trade_datetime = datetime(year, month, day, hour, minute)
                        
                        minute_data.append({
                            'stock_code': stock_code,
                            'stock_name': stock_name,
                            'trade_datetime': trade_datetime,
                            'open_price': int(open_price) if open_price else None,
                            'high_price': int(high_price) if high_price else None,
                            'low_price': int(low_price) if low_price else None,
                            'close_price': int(close_price) if close_price else None,
                            'volume': int(volume) if volume else None
                        })
                    except ValueError:
                        continue
            
            return minute_data
            
        except Exception as e:
            print(f"데이터 수집 실패 ({stock_code}): {e}")
            return None
    
    def save_stock_info(self, stock_code, stock_name):
        """종목 정보 저장"""
        if not self.connection:
            return
            
        cursor = self.connection.cursor()
        
        try:
            cursor.execute("""
                MERGE INTO STOCK_INFO target
                USING (SELECT :stock_code as STOCK_CODE, :stock_name as STOCK_NAME FROM DUAL) source
                ON (target.STOCK_CODE = source.STOCK_CODE)
                WHEN NOT MATCHED THEN
                INSERT (STOCK_CODE, STOCK_NAME) VALUES (source.STOCK_CODE, source.STOCK_NAME)
                WHEN MATCHED THEN
                UPDATE SET STOCK_NAME = source.STOCK_NAME, LAST_UPDATED = SYSDATE
            """, {'stock_code': stock_code, 'stock_name': stock_name})
            
        except Exception as e:
            print(f"종목 정보 저장 실패: {e}")
        finally:
            cursor.close()
    
    def save_minute_data(self, minute_data):
        """분봉 데이터 저장"""
        if not self.connection or not minute_data:
            return 0
            
        cursor = self.connection.cursor()
        
        merge_sql = """
        MERGE INTO STOCK_MINUTE_DATA target
        USING (
            SELECT :stock_code as STOCK_CODE,
                   :stock_name as STOCK_NAME,
                   :trade_datetime as TRADE_DATETIME,
                   :open_price as OPEN_PRICE,
                   :high_price as HIGH_PRICE,
                   :low_price as LOW_PRICE,
                   :close_price as CLOSE_PRICE,
                   :volume as VOLUME
            FROM DUAL
        ) source
        ON (target.STOCK_CODE = source.STOCK_CODE 
            AND target.TRADE_DATETIME = source.TRADE_DATETIME)
        WHEN NOT MATCHED THEN
        INSERT (STOCK_CODE, STOCK_NAME, TRADE_DATETIME, OPEN_PRICE, 
                HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, VOLUME)
        VALUES (source.STOCK_CODE, source.STOCK_NAME, source.TRADE_DATETIME,
                source.OPEN_PRICE, source.HIGH_PRICE, source.LOW_PRICE,
                source.CLOSE_PRICE, source.VOLUME)
        WHEN MATCHED THEN
        UPDATE SET 
            STOCK_NAME = source.STOCK_NAME,
            OPEN_PRICE = source.OPEN_PRICE,
            HIGH_PRICE = source.HIGH_PRICE,
            LOW_PRICE = source.LOW_PRICE,
            CLOSE_PRICE = source.CLOSE_PRICE,
            VOLUME = source.VOLUME
        """
        
        saved_count = 0
        
        try:
            for data in minute_data:
                cursor.execute(merge_sql, data)
                saved_count += 1
            
            return saved_count
            
        except Exception as e:
            print(f"❌ 데이터 저장 실패: {e}")
            return 0
        finally:
            cursor.close()
    
    def collect_and_save_all(self, count=240):
        """전체 수집 및 저장"""
        if not self.connect_db():
            return
            
        if not self.ensure_tables():
            return
        
        print("📊 오라클 분봉 데이터 수집 시작")
        print(f"📈 수집 대상: {len(self.major_stocks)}개 종목, 각 {count}개 분봉")
        print("=" * 70)
        
        total_saved = 0
        success_count = 0
        
        for stock_name, stock_code in self.major_stocks.items():
            print(f"🔍 수집 중: {stock_name} ({stock_code})")
            
            # 데이터 수집
            minute_data = self.get_minute_data(stock_code, count)
            
            if minute_data:
                print(f"  📈 {len(minute_data)}개 분봉 데이터 수집")
                
                # 종목 정보 저장
                self.save_stock_info(stock_code, stock_name)
                
                # 분봉 데이터 저장
                saved = self.save_minute_data(minute_data)
                total_saved += saved
                success_count += 1
                
                # 커밋
                self.connection.commit()
                
                # 최신 데이터 출력
                if minute_data:
                    latest = minute_data[-1]
                    dt = latest['trade_datetime']
                    print(f"  💾 {saved}개 저장")
                    print(f"  📅 최신: {dt.strftime('%m-%d %H:%M')} "
                          f"{latest['close_price']:,}원")
            else:
                print(f"  ❌ {stock_name} 데이터 수집 실패")
            
            time.sleep(0.5)  # API 제한
        
        print("=" * 70)
        print(f"✅ 총 {total_saved}개 분봉 데이터 오라클 저장 완료")
        print(f"📊 성공: {success_count}/{len(self.major_stocks)}개 종목")
        
        # 저장 통계
        self.print_stats()
    
    def print_stats(self):
        """저장 통계 출력"""
        if not self.connection:
            return
            
        cursor = self.connection.cursor()
        
        try:
            cursor.execute("""
                SELECT s.STOCK_CODE, s.STOCK_NAME, 
                       COUNT(d.ID) as DATA_COUNT,
                       MIN(d.TRADE_DATETIME) as MIN_DATE,
                       MAX(d.TRADE_DATETIME) as MAX_DATE
                FROM STOCK_INFO s
                LEFT JOIN STOCK_MINUTE_DATA d ON s.STOCK_CODE = d.STOCK_CODE
                GROUP BY s.STOCK_CODE, s.STOCK_NAME
                ORDER BY s.STOCK_CODE
            """)
            
            print("\\n📊 오라클 저장 통계:")
            print("-" * 85)
            print(f"{'종목코드':<8} {'종목명':<15} {'데이터수':<8} {'최초일시':<18} {'최신일시':<18}")
            print("-" * 85)
            
            total_records = 0
            for row in cursor.fetchall():
                code, name, count, min_date, max_date = row
                total_records += count
                
                if min_date and max_date:
                    min_str = min_date.strftime('%m-%d %H:%M')
                    max_str = max_date.strftime('%m-%d %H:%M')
                else:
                    min_str = max_str = 'N/A'
                    
                print(f"{code:<8} {name:<15} {count:<8} {min_str:<18} {max_str:<18}")
            
            print("-" * 85)
            print(f"총 데이터: {total_records:,}개 (오라클 DB)")
            
        except Exception as e:
            print(f"통계 조회 실패: {e}")
        finally:
            cursor.close()
    
    def analyze_recent(self, stock_code, hours=2):
        """최근 데이터 분석"""
        if not self.connection:
            return None
            
        cursor = self.connection.cursor()
        
        try:
            cursor.execute("""
                SELECT TRADE_DATETIME, CLOSE_PRICE, VOLUME
                FROM STOCK_MINUTE_DATA
                WHERE STOCK_CODE = :stock_code
                  AND TRADE_DATETIME >= SYSDATE - :hours/24
                  AND CLOSE_PRICE IS NOT NULL
                ORDER BY TRADE_DATETIME
            """, {'stock_code': stock_code, 'hours': hours})
            
            results = cursor.fetchall()
            
            if not results:
                return None
                
            prices = [r[1] for r in results]
            current_price = prices[-1]
            start_price = prices[0]
            change = current_price - start_price
            change_rate = (change / start_price) * 100 if start_price else 0
            
            avg_volume = sum(r[2] for r in results if r[2]) / len([r for r in results if r[2]])
            
            return {
                'stock_code': stock_code,
                'current_price': current_price,
                'change': change,
                'change_rate': change_rate,
                'avg_volume': int(avg_volume) if avg_volume else 0,
                'data_points': len(results)
            }
            
        except Exception as e:
            print(f"분석 실패: {e}")
            return None
        finally:
            cursor.close()
    
    def close(self):
        """연결 종료"""
        if self.connection:
            self.connection.close()
            print("오라클 연결 종료")

def main():
    parser = argparse.ArgumentParser(description='주식 분봉 데이터 수집기 (오라클)')
    parser.add_argument('--count', type=int, default=120, help='수집할 분봉 개수')
    parser.add_argument('--analyze', metavar='STOCK_CODE', help='종목 분석')
    
    args = parser.parse_args()
    
    collector = StockOracleCollector()
    
    try:
        if args.analyze:
            if collector.connect_db():
                analysis = collector.analyze_recent(args.analyze, 2)
                if analysis:
                    print(f"\\n📈 {args.analyze} 분석 결과 (오라클):")
                    print(f"현재가: {analysis['current_price']:,}원")
                    print(f"변동: {analysis['change']:+,}원 ({analysis['change_rate']:+.2f}%)")
                    print(f"평균거래량: {analysis['avg_volume']:,}")
                    print(f"데이터 포인트: {analysis['data_points']}개")
                else:
                    print(f"{args.analyze} 데이터 없음")
        else:
            collector.collect_and_save_all(args.count)
    finally:
        collector.close()

if __name__ == "__main__":
    main()