#!/usr/bin/env python3
"""
ETF 매매 신호 시스템
- 기술적 지표 기반 매수/매도 신호 생성
- 골든크로스, RSI, MACD, 볼린저 밴드 기반
"""

import sys
import cx_Oracle
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import json
import logging

# 로깅 설정
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('/root/.openclaw/workspace/etf_collector/trading_signals.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class TradingSignals:
    def __init__(self):
        self.db_host = 'oracle19c01'
        self.db_port = 1521
        self.db_service = 'PROD'
        self.db_user = 'stock'
        self.db_password = 'stock123'
        self.connection = None
        
        # 매매 신호 테이블 생성
        self.create_signals_table()

    def connect_db(self):
        """Oracle 데이터베이스 연결"""
        try:
            dsn = cx_Oracle.makedsn(self.db_host, self.db_port, service_name=self.db_service)
            self.connection = cx_Oracle.connect(self.db_user, self.db_password, dsn)
            logger.info(f"Oracle DB 연결 성공")
            return True
        except Exception as e:
            logger.error(f"Oracle DB 연결 실패: {e}")
            return False

    def create_signals_table(self):
        """매매 신호 테이블 생성"""
        if not self.connect_db():
            return False
        
        try:
            cursor = self.connection.cursor()
            
            # 테이블 존재 확인
            cursor.execute("""
                SELECT COUNT(*) 
                FROM user_tables 
                WHERE table_name = 'ETF_TRADING_SIGNALS'
            """)
            
            table_exists = cursor.fetchone()[0] > 0
            
            if not table_exists:
                cursor.execute("""
                    CREATE TABLE etf_trading_signals (
                        signal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        etf_code VARCHAR2(10),
                        signal_date DATE,
                        signal_type VARCHAR2(10), -- BUY, SELL, HOLD
                        signal_strength VARCHAR2(10), -- STRONG, MEDIUM, WEAK
                        price NUMBER(10,2),
                        signal_reason VARCHAR2(500),
                        indicators_json CLOB,
                        created_date DATE DEFAULT SYSDATE,
                        FOREIGN KEY (etf_code) REFERENCES etf_master(etf_code)
                    )
                """)
                
                # 인덱스 생성
                cursor.execute("CREATE INDEX idx_signals_etf_date ON etf_trading_signals(etf_code, signal_date DESC)")
                cursor.execute("CREATE INDEX idx_signals_type ON etf_trading_signals(signal_type, signal_strength)")
                
                logger.info("매매 신호 테이블 생성 완료")
            
            cursor.close()
            return True
            
        except Exception as e:
            logger.error(f"매매 신호 테이블 생성 실패: {e}")
            return False

    def get_latest_technical_data(self, etf_code, days=5):
        """최근 기술적 지표 데이터 조회 (현재 가용한 지표만)"""
        try:
            cursor = self.connection.cursor()
            
            cursor.execute("""
                SELECT trade_date, close_price, 
                       sma_5, sma_20,
                       rsi_14, 
                       volume
                FROM etf_technical_indicators
                WHERE etf_code = :etf_code
                ORDER BY trade_date DESC
                FETCH FIRST :days ROWS ONLY
            """, {'etf_code': etf_code, 'days': days})
            
            rows = cursor.fetchall()
            cursor.close()
            
            if not rows:
                return None
            
            # DataFrame으로 변환 (최신 순 → 오래된 순으로 정렬)
            columns = ['date', 'close', 'sma_5', 'sma_20', 'rsi_14', 'volume']
            
            df = pd.DataFrame(rows, columns=columns)
            df = df.iloc[::-1]  # 오래된 순으로 정렬
            df.reset_index(drop=True, inplace=True)
            
            return df
            
        except Exception as e:
            logger.error(f"{etf_code} 기술적 데이터 조회 실패: {e}")
            return None

    def analyze_trend_signals(self, df):
        """추세 기반 신호 분석 (간단 버전)"""
        signals = []
        latest = df.iloc[-1]  # 최신 데이터
        prev = df.iloc[-2] if len(df) > 1 else None  # 전날 데이터
        
        # SMA 5 vs 20 기반 분석
        if pd.notna(latest['sma_5']) and pd.notna(latest['sma_20']):
            # 1. 골든크로스 / 데드크로스 (SMA 5 vs 20)
            if prev is not None and pd.notna(prev['sma_5']) and pd.notna(prev['sma_20']):
                if latest['sma_5'] > latest['sma_20'] and prev['sma_5'] <= prev['sma_20']:
                    signals.append({
                        'type': 'BUY',
                        'strength': 'STRONG', 
                        'reason': 'Golden Cross (SMA5 > SMA20)',
                        'source': 'TREND'
                    })
                elif latest['sma_5'] < latest['sma_20'] and prev['sma_5'] >= prev['sma_20']:
                    signals.append({
                        'type': 'SELL',
                        'strength': 'STRONG',
                        'reason': 'Dead Cross (SMA5 < SMA20)',
                        'source': 'TREND'
                    })
            
            # 2. 단순 추세 분석
            if latest['sma_5'] > latest['sma_20']:
                signals.append({
                    'type': 'BUY',
                    'strength': 'MEDIUM',
                    'reason': 'SMA5 > SMA20 (Uptrend)',
                    'source': 'TREND'
                })
            else:
                signals.append({
                    'type': 'SELL',
                    'strength': 'MEDIUM',
                    'reason': 'SMA5 < SMA20 (Downtrend)',
                    'source': 'TREND'
                })
        
        return signals

    def analyze_momentum_signals(self, df):
        """모멘텀 기반 신호 분석 (간단 버전)"""
        signals = []
        latest = df.iloc[-1]
        
        # RSI 과매수/과매도 (현재 가용한 지표)
        if pd.notna(latest['rsi_14']):
            rsi = latest['rsi_14']
            if rsi < 30:
                strength = 'STRONG' if rsi < 20 else 'MEDIUM'
                signals.append({
                    'type': 'BUY',
                    'strength': strength,
                    'reason': f'RSI Oversold ({rsi:.1f})',
                    'source': 'RSI'
                })
            elif rsi > 70:
                strength = 'STRONG' if rsi > 80 else 'MEDIUM'
                signals.append({
                    'type': 'SELL',
                    'strength': strength,
                    'reason': f'RSI Overbought ({rsi:.1f})',
                    'source': 'RSI'
                })
        
        return signals

    def analyze_bollinger_signals(self, df):
        """볼린저 밴드 기반 신호 분석"""
        signals = []
        latest = df.iloc[-1]
        
        # 볼린저 밴드 위치 분석
        bb_position = (latest['close'] - latest['bb_lower']) / (latest['bb_upper'] - latest['bb_lower'])
        
        # 하단 근처 (과매도)
        if bb_position < 0.1:
            signals.append({
                'type': 'BUY',
                'strength': 'MEDIUM',
                'reason': f'Bollinger Lower Band Touch ({bb_position:.2f})',
                'source': 'BOLLINGER'
            })
        
        # 상단 근처 (과매수)
        elif bb_position > 0.9:
            signals.append({
                'type': 'SELL',
                'strength': 'MEDIUM',
                'reason': f'Bollinger Upper Band Touch ({bb_position:.2f})',
                'source': 'BOLLINGER'
            })
        
        # 볼린저 밴드 폭 분석 (변동성)
        if latest['bb_width'] < 5:  # 낮은 변동성
            signals.append({
                'type': 'HOLD',
                'strength': 'WEAK',
                'reason': f'Low Volatility ({latest["bb_width"]:.1f}%)',
                'source': 'BOLLINGER'
            })
        elif latest['bb_width'] > 15:  # 높은 변동성
            signals.append({
                'type': 'HOLD',
                'strength': 'WEAK',
                'reason': f'High Volatility ({latest["bb_width"]:.1f}%)',
                'source': 'BOLLINGER'
            })
        
        return signals

    def analyze_volume_signals(self, df):
        """거래량 기반 신호 분석"""
        signals = []
        latest = df.iloc[-1]
        
        # 거래량 급증
        volume_ratio = latest['volume'] / latest['volume_sma_20'] if latest['volume_sma_20'] > 0 else 1
        
        if volume_ratio > 2.0:  # 평균 대비 2배 이상
            signals.append({
                'type': 'HOLD',
                'strength': 'MEDIUM',
                'reason': f'Volume Surge ({volume_ratio:.1f}x avg)',
                'source': 'VOLUME'
            })
        elif volume_ratio < 0.5:  # 평균 대비 절반 이하
            signals.append({
                'type': 'HOLD',
                'strength': 'WEAK',
                'reason': f'Low Volume ({volume_ratio:.1f}x avg)',
                'source': 'VOLUME'
            })
        
        return signals

    def generate_final_signal(self, all_signals):
        """최종 매매 신호 생성"""
        if not all_signals:
            return {
                'type': 'HOLD',
                'strength': 'WEAK',
                'reason': 'No clear signals',
                'details': []
            }
        
        # 신호 점수 계산
        buy_score = 0
        sell_score = 0
        
        strength_weights = {'STRONG': 3, 'MEDIUM': 2, 'WEAK': 1}
        
        for signal in all_signals:
            weight = strength_weights.get(signal['strength'], 1)
            
            if signal['type'] == 'BUY':
                buy_score += weight
            elif signal['type'] == 'SELL':
                sell_score += weight
        
        # 최종 신호 결정
        score_diff = abs(buy_score - sell_score)
        
        if buy_score > sell_score:
            signal_type = 'BUY'
            if score_diff >= 4:
                strength = 'STRONG'
            elif score_diff >= 2:
                strength = 'MEDIUM'
            else:
                strength = 'WEAK'
        elif sell_score > buy_score:
            signal_type = 'SELL'
            if score_diff >= 4:
                strength = 'STRONG'
            elif score_diff >= 2:
                strength = 'MEDIUM'
            else:
                strength = 'WEAK'
        else:
            signal_type = 'HOLD'
            strength = 'WEAK'
        
        # 주요 신호 이유 추출
        main_reasons = []
        strong_signals = [s for s in all_signals if s['strength'] == 'STRONG']
        medium_signals = [s for s in all_signals if s['strength'] == 'MEDIUM']
        
        if strong_signals:
            main_reasons = [s['reason'] for s in strong_signals]
        elif medium_signals:
            main_reasons = [s['reason'] for s in medium_signals[:2]]  # 상위 2개
        else:
            main_reasons = [s['reason'] for s in all_signals[:2]]
        
        return {
            'type': signal_type,
            'strength': strength,
            'reason': ' | '.join(main_reasons),
            'buy_score': buy_score,
            'sell_score': sell_score,
            'details': all_signals
        }

    def save_trading_signal(self, etf_code, signal_data, indicators_data):
        """매매 신호를 DB에 저장"""
        try:
            cursor = self.connection.cursor()
            
            cursor.execute("""
                INSERT INTO etf_trading_signals 
                (etf_code, signal_date, signal_type, signal_strength, price, 
                 signal_reason, indicators_json, created_date)
                VALUES (:etf_code, SYSDATE, :signal_type, :signal_strength, :price,
                        :signal_reason, :indicators_json, SYSDATE)
            """, {
                'etf_code': etf_code,
                'signal_type': signal_data['type'],
                'signal_strength': signal_data['strength'],
                'price': float(indicators_data.iloc[-1]['close']),
                'signal_reason': signal_data['reason'],
                'indicators_json': json.dumps({
                    'buy_score': signal_data['buy_score'],
                    'sell_score': signal_data['sell_score'],
                    'details': signal_data['details']
                }, ensure_ascii=False)
            })
            
            self.connection.commit()
            cursor.close()
            return True
            
        except Exception as e:
            logger.error(f"{etf_code} 매매 신호 저장 실패: {e}")
            return False

    def analyze_etf_signals(self, etf_code):
        """개별 ETF 매매 신호 분석"""
        logger.info(f"[{etf_code}] 매매 신호 분석 중...")
        
        # 기술적 데이터 조회
        df = self.get_latest_technical_data(etf_code, days=5)
        if df is None or len(df) < 1:
            logger.warning(f"{etf_code}: 기술적 데이터 없음")
            return None
        
        # 단일 데이터만 있을 때 단순 분석 모드
        if len(df) == 1:
            return self.analyze_single_data_signals(etf_code, df.iloc[0])
        
        # 각 분야별 신호 분석 (현재 가용한 지표만)
        trend_signals = self.analyze_trend_signals(df)
        momentum_signals = self.analyze_momentum_signals(df)
        
        # 모든 신호 통합
        all_signals = trend_signals + momentum_signals
        
        # 최종 신호 생성
        final_signal = self.generate_final_signal(all_signals)
        
        # DB 저장
        if self.save_trading_signal(etf_code, final_signal, df):
            logger.info(f"{etf_code}: {final_signal['type']} ({final_signal['strength']}) - {final_signal['reason']}")
        
        return final_signal

    def analyze_single_data_signals(self, etf_code, data):
        """단일 데이터 기반 매매 신호 분석 (간단 버전)"""
        signals = []
        
        # 1. RSI 기반 신호
        if 'rsi_14' in data and pd.notna(data['rsi_14']):
            rsi = data['rsi_14']
            if rsi < 30:
                strength = 'STRONG' if rsi < 20 else 'MEDIUM'
                signals.append({
                    'type': 'BUY',
                    'strength': strength,
                    'reason': f'RSI Oversold ({rsi:.1f})',
                    'source': 'RSI'
                })
            elif rsi > 70:
                strength = 'STRONG' if rsi > 80 else 'MEDIUM'
                signals.append({
                    'type': 'SELL',
                    'strength': strength,
                    'reason': f'RSI Overbought ({rsi:.1f})',
                    'source': 'RSI'
                })
        
        # 2. 이동평균 기반 신호
        if ('sma_5' in data and 'sma_20' in data and 
            pd.notna(data['sma_5']) and pd.notna(data['sma_20'])):
            if data['sma_5'] > data['sma_20']:
                signals.append({
                    'type': 'BUY',
                    'strength': 'MEDIUM',
                    'reason': 'SMA5 > SMA20 (Uptrend)',
                    'source': 'TREND'
                })
            else:
                signals.append({
                    'type': 'SELL',
                    'strength': 'MEDIUM',
                    'reason': 'SMA5 < SMA20 (Downtrend)',
                    'source': 'TREND'
                })
        
        # 최종 신호 생성
        final_signal = self.generate_final_signal(signals)
        
        # DataFrame 형태로 변환하여 저장 함수와 호환
        df_single = pd.DataFrame([data])
        
        # DB 저장
        if self.save_trading_signal(etf_code, final_signal, df_single):
            logger.info(f"{etf_code}: {final_signal['type']} ({final_signal['strength']}) - {final_signal['reason']}")
        
        return final_signal

    def run_signal_analysis(self):
        """전체 ETF 매매 신호 분석"""
        logger.info("=== ETF 매매 신호 분석 시작 ===")
        
        if not self.connect_db():
            return False
        
        try:
            # ETF 목록 조회
            cursor = self.connection.cursor()
            cursor.execute("SELECT etf_code, etf_name FROM etf_master ORDER BY etf_code")
            etf_list = cursor.fetchall()
            cursor.close()
            
            results = []
            
            for etf_code, etf_name in etf_list:
                signal = self.analyze_etf_signals(etf_code)
                if signal:
                    results.append({
                        'etf_code': etf_code,
                        'etf_name': etf_name,
                        'signal': signal
                    })
            
            # 결과 요약 출력
            self.print_signal_summary(results)
            
            logger.info(f"=== 매매 신호 분석 완료: {len(results)}개 ETF ===")
            return True
            
        except Exception as e:
            logger.error(f"매매 신호 분석 실패: {e}")
            return False
            
        finally:
            if self.connection:
                self.connection.close()

    def print_signal_summary(self, results):
        """매매 신호 요약 출력"""
        print("\n" + "="*80)
        print("🎯 ETF 매매 신호 분석 결과")
        print("="*80)
        
        buy_signals = []
        sell_signals = []
        hold_signals = []
        
        for result in results:
            signal = result['signal']
            if signal['type'] == 'BUY':
                buy_signals.append(result)
            elif signal['type'] == 'SELL':
                sell_signals.append(result)
            else:
                hold_signals.append(result)
        
        # 매수 신호
        if buy_signals:
            print(f"\n🟢 매수 신호 ({len(buy_signals)}개)")
            print("-" * 60)
            for result in buy_signals:
                strength_emoji = {"STRONG": "🔥", "MEDIUM": "📈", "WEAK": "📊"}
                emoji = strength_emoji.get(result['signal']['strength'], "📊")
                print(f"{emoji} {result['etf_code']} {result['etf_name'][:15]:<15} "
                      f"({result['signal']['strength']:<6}) {result['signal']['reason'][:50]}")
        
        # 매도 신호
        if sell_signals:
            print(f"\n🔴 매도 신호 ({len(sell_signals)}개)")
            print("-" * 60)
            for result in sell_signals:
                strength_emoji = {"STRONG": "💥", "MEDIUM": "📉", "WEAK": "📊"}
                emoji = strength_emoji.get(result['signal']['strength'], "📊")
                print(f"{emoji} {result['etf_code']} {result['etf_name'][:15]:<15} "
                      f"({result['signal']['strength']:<6}) {result['signal']['reason'][:50]}")
        
        # 보유 신호  
        if hold_signals:
            print(f"\n⚪ 보유 신호 ({len(hold_signals)}개)")
            print("-" * 60)
            for result in hold_signals:
                print(f"⚪ {result['etf_code']} {result['etf_name'][:15]:<15} "
                      f"({result['signal']['strength']:<6}) {result['signal']['reason'][:50]}")

def main():
    """메인 함수"""
    signal_analyzer = TradingSignals()
    success = signal_analyzer.run_signal_analysis()
    
    if success:
        print("✅ ETF 매매 신호 분석 성공!")
        sys.exit(0)
    else:
        print("❌ ETF 매매 신호 분석 실패!")
        sys.exit(1)

if __name__ == "__main__":
    main()