services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.7
    container_name: zookeeper
    network_mode: host

  kafka:
    image: quay.io/debezium/kafka:2.7
    container_name: kafka
    network_mode: host
    environment:
      ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  connect:
    image: quay.io/debezium/connect:2.7
    container_name: connect
    network_mode: host
    environment:
      BOOTSTRAP_SERVERS: localhost:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
    depends_on:
      - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9091:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: debezium-cdc
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.50.56:9092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium-connect
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://192.168.50.56:8083
    depends_on:
      - kafka
      - connect
