#!/usr/bin/env python3
"""
ETF 자동매매 시스템 데이터베이스 설정
Oracle 데이터베이스에 필요한 테이블과 인덱스를 생성합니다.
"""

import cx_Oracle
import yaml
import sys
import os

def load_config():
    """설정 파일 로드"""
    with open('config.yaml', 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def connect_database(config):
    """데이터베이스 연결"""
    db_config = config['database']
    
    dsn = cx_Oracle.makedsn(
        db_config['host'], 
        db_config['port'], 
        service_name=db_config['service']
    )
    
    connection = cx_Oracle.connect(
        db_config['user'],
        db_config['password'], 
        dsn
    )
    
    return connection

def create_tables(connection):
    """테이블 생성"""
    cursor = connection.cursor()
    
    print("📊 ETF 마스터 테이블 생성 중...")
    cursor.execute("""
        CREATE TABLE etf_master (
            etf_code VARCHAR2(10) PRIMARY KEY,
            etf_name VARCHAR2(100) NOT NULL,
            underlying_index VARCHAR2(100),
            category VARCHAR2(50),
            expense_ratio NUMBER(5,4),
            nav NUMBER(12,2),
            created_date DATE DEFAULT SYSDATE,
            updated_date DATE DEFAULT SYSDATE
        )
    """)
    
    print("📈 ETF 일별 가격 테이블 생성 중...")
    cursor.execute("""
        CREATE TABLE etf_daily_price (
            etf_code VARCHAR2(10),
            trade_date DATE,
            open_price NUMBER(10,2),
            high_price NUMBER(10,2),
            low_price NUMBER(10,2),
            close_price NUMBER(10,2),
            volume NUMBER(15),
            nav NUMBER(10,2),
            tracking_error NUMBER(6,4),
            created_date DATE DEFAULT SYSDATE,
            PRIMARY KEY (etf_code, trade_date),
            FOREIGN KEY (etf_code) REFERENCES etf_master(etf_code)
        )
    """)
    
    print("🧮 ETF 기술적 지표 테이블 생성 중...")
    cursor.execute("""
        CREATE TABLE etf_technical_indicators (
            etf_code VARCHAR2(10),
            trade_date DATE,
            close_price NUMBER(10,2),
            sma_5 NUMBER(10,2),
            sma_20 NUMBER(10,2),
            sma_60 NUMBER(10,2),
            sma_200 NUMBER(10,2),
            ema_5 NUMBER(10,2),
            ema_20 NUMBER(10,2),
            ema_60 NUMBER(10,2),
            ema_200 NUMBER(10,2),
            rsi_14 NUMBER(5,2),
            macd_line NUMBER(10,4),
            macd_signal NUMBER(10,4),
            macd_histogram NUMBER(10,4),
            bb_upper NUMBER(10,2),
            bb_middle NUMBER(10,2),
            bb_lower NUMBER(10,2),
            bb_width NUMBER(10,4),
            volume NUMBER(15),
            volume_sma_20 NUMBER(15),
            created_date DATE DEFAULT SYSDATE,
            updated_date DATE DEFAULT SYSDATE,
            PRIMARY KEY (etf_code, trade_date),
            FOREIGN KEY (etf_code) REFERENCES etf_master(etf_code)
        )
    """)
    
    print("🎯 매매 신호 테이블 생성 중...")
    cursor.execute("""
        CREATE TABLE etf_trading_signals (
            signal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            etf_code VARCHAR2(10),
            signal_date DATE,
            signal_type VARCHAR2(10),
            signal_strength VARCHAR2(10),
            price NUMBER(10,2),
            signal_reason VARCHAR2(500),
            indicators_json CLOB,
            created_date DATE DEFAULT SYSDATE,
            FOREIGN KEY (etf_code) REFERENCES etf_master(etf_code)
        )
    """)
    
    print("⚡ 실시간 가격 테이블 생성 중...")
    cursor.execute("""
        CREATE TABLE etf_realtime_price (
            etf_code VARCHAR2(10) PRIMARY KEY,
            current_price NUMBER(10,2),
            open_price NUMBER(10,2),
            high_price NUMBER(10,2),
            low_price NUMBER(10,2),
            volume NUMBER(15),
            change_rate NUMBER(8,4),
            update_time DATE,
            FOREIGN KEY (etf_code) REFERENCES etf_master(etf_code)
        )
    """)
    
    print("📊 ETF 구성종목 테이블 생성 중...")
    cursor.execute("""
        CREATE TABLE etf_holdings (
            etf_code VARCHAR2(10),
            stock_code VARCHAR2(10),
            stock_name VARCHAR2(100),
            weight_ratio NUMBER(6,4),
            shares NUMBER(15),
            market_value NUMBER(15),
            update_date DATE,
            PRIMARY KEY (etf_code, stock_code, update_date),
            FOREIGN KEY (etf_code) REFERENCES etf_master(etf_code)
        )
    """)
    
    cursor.close()

def create_indexes(connection):
    """인덱스 생성"""
    cursor = connection.cursor()
    
    print("🔍 인덱스 생성 중...")
    
    indexes = [
        "CREATE INDEX idx_etf_price_date ON etf_daily_price(trade_date)",
        "CREATE INDEX idx_tech_etf_date ON etf_technical_indicators(etf_code, trade_date DESC)",
        "CREATE INDEX idx_tech_date ON etf_technical_indicators(trade_date)",
        "CREATE INDEX idx_signals_etf_date ON etf_trading_signals(etf_code, signal_date DESC)",
        "CREATE INDEX idx_signals_type ON etf_trading_signals(signal_type, signal_strength)",
        "CREATE INDEX idx_holdings_date ON etf_holdings(update_date)",
        "CREATE INDEX idx_realtime_update ON etf_realtime_price(update_time)"
    ]
    
    for index_sql in indexes:
        try:
            cursor.execute(index_sql)
            print(f"  ✅ {index_sql.split()[2]} 생성 완료")
        except Exception as e:
            print(f"  ⚠️ 인덱스 생성 실패: {e}")
    
    cursor.close()

def insert_etf_master_data(connection, config):
    """ETF 마스터 데이터 삽입"""
    cursor = connection.cursor()
    
    print("📋 ETF 마스터 데이터 삽입 중...")
    
    etf_data = [
        ('069500', 'KODEX 200', 'KOSPI 200', 'Large Cap', 0.0015),
        ('229200', 'KODEX KOSDAQ150', 'KOSDAQ 150', 'KOSDAQ', 0.0015),
        ('102110', 'TIGER 200IT', 'KOSPI 200 IT', 'IT Sector', 0.0015),
        ('133690', 'TIGER NASDAQ100', 'NASDAQ 100', 'US Tech', 0.0045),
        ('449180', 'KODEX US SP500', 'SP500 TR', 'US Large Cap', 0.0008),
        ('161510', 'KODEX High Dividend', 'High Dividend', 'Dividend', 0.0025),
        ('091230', 'KODEX Battery', 'Battery Industry', 'Battery', 0.0045),
        ('160580', 'KODEX Samsung Pref', 'Samsung Preferred', 'Preferred', 0.0015),
        ('091170', 'TIGER Construction', 'KOSPI Construction', 'Construction', 0.0015),
        ('130680', 'TIGER Oil Futures', 'Oil Futures', 'Commodity', 0.0045)
    ]
    
    insert_sql = """
        INSERT INTO etf_master (etf_code, etf_name, underlying_index, category, expense_ratio, created_date, updated_date)
        VALUES (:1, :2, :3, :4, :5, SYSDATE, SYSDATE)
    """
    
    cursor.executemany(insert_sql, etf_data)
    
    print(f"  ✅ {len(etf_data)}개 ETF 마스터 데이터 삽입 완료")
    cursor.close()

def setup_sequences(connection):
    """시퀀스 생성 (필요시)"""
    cursor = connection.cursor()
    
    print("🔢 시퀀스 생성 중...")
    
    try:
        cursor.execute("""
            CREATE SEQUENCE etf_signal_seq
            START WITH 1
            INCREMENT BY 1
            NOCACHE
        """)
        print("  ✅ etf_signal_seq 시퀀스 생성 완료")
    except Exception as e:
        print(f"  ⚠️ 시퀀스 생성 실패 (이미 존재할 수 있음): {e}")
    
    cursor.close()

def main():
    """메인 함수"""
    print("🚀 ETF 자동매매 시스템 데이터베이스 설정 시작")
    print("="*60)
    
    try:
        # 설정 파일 로드
        config = load_config()
        print("📄 설정 파일 로드 완료")
        
        # 데이터베이스 연결
        print("🔌 데이터베이스 연결 중...")
        connection = connect_database(config)
        print("  ✅ 데이터베이스 연결 성공")
        
        # 테이블 생성
        create_tables(connection)
        
        # 인덱스 생성
        create_indexes(connection)
        
        # 시퀀스 생성
        setup_sequences(connection)
        
        # 마스터 데이터 삽입
        insert_etf_master_data(connection, config)
        
        # 커밋
        connection.commit()
        print("💾 모든 변경사항 커밋 완료")
        
        # 연결 종료
        connection.close()
        print("🔐 데이터베이스 연결 종료")
        
        print("="*60)
        print("✅ 데이터베이스 설정 완료!")
        print("")
        print("다음 단계:")
        print("1. python3 generate_historical_data.py  # 시뮬레이션 데이터 생성")
        print("2. python3 technical_analyzer.py        # 기술적 지표 계산")  
        print("3. python3 trading_signals.py           # 매매 신호 생성")
        
        return True
        
    except Exception as e:
        print(f"❌ 데이터베이스 설정 실패: {e}")
        return False

if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)