-- ============================================
-- Blog Application DDL
-- Target: app_user@PROD (192.168.50.35)
-- Generated from blog-api source analysis
-- ============================================

-- 1. BLOG_USER
CREATE TABLE BLOG_USER (
    ID              NUMBER        NOT NULL,
    USERNAME        VARCHAR2(100) NOT NULL,
    PASSWORD        VARCHAR2(200) NOT NULL,
    EMAIL           VARCHAR2(200),
    NICKNAME        VARCHAR2(100) NOT NULL,
    ROLE            VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
    IS_ACTIVE       CHAR(1)       DEFAULT 'Y' NOT NULL,
    PROFILE_IMG     VARCHAR2(500),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    LAST_LOGIN      TIMESTAMP,
    CONSTRAINT PK_BLOG_USER PRIMARY KEY (ID),
    CONSTRAINT UK_BLOG_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_BLOG_USER_NICKNAME UNIQUE (NICKNAME),
    CONSTRAINT CK_BLOG_USER_ROLE CHECK (ROLE IN ('ADMIN', 'USER')),
    CONSTRAINT CK_BLOG_USER_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_BLOG_USER START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2. BLOG_CATEGORY
CREATE TABLE BLOG_CATEGORY (
    ID              NUMBER        NOT NULL,
    NAME            VARCHAR2(100) NOT NULL,
    DESCRIPTION     VARCHAR2(500),
    SORT_ORDER      NUMBER        DEFAULT 0 NOT NULL,
    IS_ACTIVE       CHAR(1)       DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_BLOG_CATEGORY PRIMARY KEY (ID),
    CONSTRAINT CK_BLOG_CATEGORY_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_BLOG_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE;

-- 3. BLOG_POST
CREATE TABLE BLOG_POST (
    ID              NUMBER         NOT NULL,
    TITLE           VARCHAR2(500)  NOT NULL,
    CONTENT         CLOB,
    EXCERPT         VARCHAR2(1000),
    AUTHOR_ID       NUMBER         NOT NULL,
    CATEGORY_ID     NUMBER,
    THUMBNAIL       VARCHAR2(500),
    VIEW_COUNT      NUMBER         DEFAULT 0 NOT NULL,
    LIKE_COUNT      NUMBER         DEFAULT 0 NOT NULL,
    COMMENT_COUNT   NUMBER         DEFAULT 0 NOT NULL,
    STATUS          VARCHAR2(20)   DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP,
    PUBLISHED_AT    TIMESTAMP,
    CONSTRAINT PK_BLOG_POST PRIMARY KEY (ID),
    CONSTRAINT FK_BLOG_POST_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES BLOG_USER(ID),
    CONSTRAINT FK_BLOG_POST_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES BLOG_CATEGORY(ID),
    CONSTRAINT CK_BLOG_POST_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE SEQUENCE SEQ_BLOG_POST START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_BLOG_POST_AUTHOR ON BLOG_POST(AUTHOR_ID);
CREATE INDEX IDX_BLOG_POST_CATEGORY ON BLOG_POST(CATEGORY_ID);
CREATE INDEX IDX_BLOG_POST_STATUS ON BLOG_POST(STATUS);
CREATE INDEX IDX_BLOG_POST_CREATED ON BLOG_POST(CREATED_AT DESC);

-- 4. BLOG_COMMENT
CREATE TABLE BLOG_COMMENT (
    ID              NUMBER         NOT NULL,
    POST_ID         NUMBER         NOT NULL,
    AUTHOR_ID       NUMBER         NOT NULL,
    PARENT_ID       NUMBER,
    CONTENT         VARCHAR2(4000) NOT NULL,
    IS_DELETED      CHAR(1)        DEFAULT 'N' NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT PK_BLOG_COMMENT PRIMARY KEY (ID),
    CONSTRAINT FK_BLOG_COMMENT_POST FOREIGN KEY (POST_ID) REFERENCES BLOG_POST(ID),
    CONSTRAINT FK_BLOG_COMMENT_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES BLOG_USER(ID),
    CONSTRAINT FK_BLOG_COMMENT_PARENT FOREIGN KEY (PARENT_ID) REFERENCES BLOG_COMMENT(ID),
    CONSTRAINT CK_BLOG_COMMENT_DEL CHECK (IS_DELETED IN ('Y', 'N'))
);

CREATE SEQUENCE SEQ_BLOG_COMMENT START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_BLOG_COMMENT_POST ON BLOG_COMMENT(POST_ID);

-- 5. BLOG_FILE
CREATE TABLE BLOG_FILE (
    ID              NUMBER         NOT NULL,
    ORIGINAL_NAME   VARCHAR2(500)  NOT NULL,
    STORED_NAME     VARCHAR2(200)  NOT NULL,
    FILE_PATH       VARCHAR2(1000) NOT NULL,
    FILE_SIZE       NUMBER         NOT NULL,
    FILE_TYPE       VARCHAR2(100)  NOT NULL,
    UPLOADER_ID     NUMBER         NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BLOG_FILE PRIMARY KEY (ID),
    CONSTRAINT FK_BLOG_FILE_UPLOADER FOREIGN KEY (UPLOADER_ID) REFERENCES BLOG_USER(ID)
);

CREATE SEQUENCE SEQ_BLOG_FILE START WITH 1 INCREMENT BY 1 NOCACHE;

-- 6. AI_API_CALLS (AI 비용 모니터링)
CREATE TABLE AI_API_CALLS (
    CALL_UUID        VARCHAR2(100)  NOT NULL,
    CALLED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    MODEL_NAME       VARCHAR2(100),
    MODEL_TIER       VARCHAR2(20),
    INPUT_TOKENS     NUMBER         DEFAULT 0,
    OUTPUT_TOKENS    NUMBER         DEFAULT 0,
    TOTAL_COST_USD   NUMBER(12,6)   DEFAULT 0,
    RESPONSE_TIME_MS NUMBER,
    REQUEST_SOURCE   VARCHAR2(100),
    ERROR_CODE       VARCHAR2(100),
    CONSTRAINT PK_AI_API_CALLS PRIMARY KEY (CALL_UUID)
);

CREATE INDEX IDX_AI_API_CALLS_DATE ON AI_API_CALLS(CALLED_AT DESC);
CREATE INDEX IDX_AI_API_CALLS_MODEL ON AI_API_CALLS(MODEL_NAME);

-- 7. AI_DAILY_STATS (일별 집계)
CREATE TABLE AI_DAILY_STATS (
    STAT_DATE           DATE          NOT NULL,
    MODEL_TIER          VARCHAR2(20)  NOT NULL,
    CALL_COUNT          NUMBER        DEFAULT 0,
    TOTAL_INPUT_TOKENS  NUMBER        DEFAULT 0,
    TOTAL_OUTPUT_TOKENS NUMBER        DEFAULT 0,
    TOTAL_COST_USD      NUMBER(12,6)  DEFAULT 0,
    CONSTRAINT PK_AI_DAILY_STATS PRIMARY KEY (STAT_DATE, MODEL_TIER)
);

-- 8. V_MONTHLY_COST_SUMMARY (월별 뷰)
CREATE OR REPLACE VIEW V_MONTHLY_COST_SUMMARY AS
SELECT
    TO_CHAR(STAT_DATE, 'YYYY-MM')  AS MONTH_STR,
    MODEL_TIER,
    SUM(CALL_COUNT)                AS TOTAL_CALLS,
    SUM(TOTAL_INPUT_TOKENS)        AS TOTAL_INPUT_TOKENS,
    SUM(TOTAL_OUTPUT_TOKENS)       AS TOTAL_OUTPUT_TOKENS,
    ROUND(SUM(TOTAL_COST_USD), 4)  AS TOTAL_COST_USD,
    ROUND(AVG(TOTAL_COST_USD / NULLIF(CALL_COUNT, 0) * 1000), 1) AS AVG_RESPONSE_MS
FROM AI_DAILY_STATS
GROUP BY TO_CHAR(STAT_DATE, 'YYYY-MM'), MODEL_TIER
ORDER BY 1 DESC, 2;

-- 관리자 계정 (비밀번호: admin123 → bcrypt hash)
-- 필요 시 INSERT 후 앱에서 비밀번호 변경
-- INSERT INTO BLOG_USER (ID, USERNAME, PASSWORD, NICKNAME, ROLE)
-- VALUES (SEQ_BLOG_USER.NEXTVAL, 'admin', '$2b$10$...hash...', '관리자', 'ADMIN');

COMMIT;
